# Generated by Django 3.2.6 on 2021-11-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'dark')], default='light', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='setting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usersetting'),
        ),
    ]
